Zem1/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Zem.Web.Models;
using Zem1.Data.Models;

namespace Zem.Web.Controllers
{
    public class EditorController : BaseController
    {
        private readonly ILogger<EditorController> _logger;

        public EditorController(ILogger<EditorController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> IndexAsync()
        {
            SetSessionAndBaseUrl();

            List<Post> postsList = new List<Post>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(baseUrl + "api/Post/GetPending"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    postsList = JsonConvert.DeserializeObject<List<Post>>(apiResponse);
                }
            }
            var vModel = new PostsViewModel { Posts = postsList };

            return View(vModel);
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Zem1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Zem.Web.Models;
using Zem1.Data.Models;

namespace Zem.Web.Controllers
{
    public class LoginController : BaseController
    {
        private readonly ILogger<LoginController> _logger;

        const string SessionUserId = "_UserId";
        const string SessionUsername = "_Username";
        const string SessionRole = "_Role";

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            SetSessionAndBaseUrl();

            ViewData["isValid"] = "";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginAsync(string username, string password)
        {
            SetSessionAndBaseUrl();

            User user = new User();
            using (var httpClient = new HttpClient())
            {
                var stringContent = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("username", username),
                    new KeyValuePair<string, string>("password", password),
                });
                var parameters = new Dictionary<string, string> { { "username", username }, { "password", password } };
                var encodedContent = new FormUrlEncodedContent(parameters);
                var url = $"{baseUrl}api/Login/ValidateUser?username={username}&password={password}";

                using (var response = await httpClient.PostAsync(url, null))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    user = JsonConvert.DeserializeObject<User>(apiResponse);

                    if (user != null)
                    {
                        HttpContext.Session.SetInt32(SessionUserId, user.UserId);
                        HttpContext.Session.SetString(SessionUsername, user.Username);

                        if (user.Role.RoleId == 2)
                        {
                            HttpContext.Session.SetString(SessionRole, "writer");
                            return Redirect("../Writer/Index/" + user.UserId);
                        }
                        else if (user.Role.RoleId == 3)
                        {
                            HttpContext.Session.SetString(SessionRole, "editor");
                            return Redirect("../Editor/Index/" + user.UserId);
                        }
                        else
                        {
                            HttpContext.Session.SetString(SessionRole, "normal");
                            return Redirect("../Home/");
                        }

                    }
                }
            }

            ViewData["isValid"] = "no";
            return View("Index");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.SetInt32(SessionUserId, 0);
            HttpContext.Session.SetString(SessionUsername, "");
            HttpContext.Session.SetString(SessionRole, "");

            return Redirect("../Home/");
        }

    }
}

Zem1/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Zem.Web.Models;
using Zem1.Data.Models;

namespace Zem.Web.Controllers
{
    public class WriterController : BaseController
    {
        private readonly ILogger<WriterController> _logger;

        public WriterController(ILogger<WriterController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> IndexAsync(int id)
        {
            SetSessionAndBaseUrl();

            List<Post> postsList = new List<Post>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(baseUrl + "api/Post/GetMyPosts/" + id ))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    postsList = JsonConvert.DeserializeObject<List<Post>>(apiResponse);
                }
            }
            var vModel = new PostsViewModel { Posts = postsList };

            return View(vModel);
        }

        public async Task<IActionResult> Write(Nullable<Guid> id = null, string pageType = "create")
        {
            SetSessionAndBaseUrl();
            var vModel = new PostInfoViewModel {PageType = pageType };

            if (pageType == "edit")
            {
                Post postInfo = new Post();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync("http://localhost:50219/api/Post/" + id))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        postInfo = JsonConvert.DeserializeObject<Post>(apiResponse);
                    }
                }
                vModel.PostInfo = postInfo;
            }
            return View(vModel);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Zem1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zem.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if ((string)ViewData["SessionRole"] == "writer")
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Writer" asp-action="Index" asp-route-id="@ViewData["SessionUserId"]">My Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Writer" asp-action="Write" asp-route-id="@ViewData["SessionUserId"]">Write Post</a>
                        </li>
                    } else
                    @if ((string)ViewData["SessionRole"] == "editor")
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Editor" asp-action="Index" asp-route-id="@ViewData["SessionUserId"]">Approve Posts</a>
                        </li>
                    }
                </ul>
            </div>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">

                    @if ((string)ViewData["SessionRole"] == "writer" || (string)ViewData["SessionRole"] == "editor")
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Zem.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>